"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "DevToys/DevToys/Resource/en.lproj/*.strings",
    "translation": "DevToys/DevToys/Resource/%osx_locale%.lproj/%original_file_name%",
    "languages_mapping": {
      "osx_locale": {
        "pt-BR": "pt-BR",
        "zh-CN": "zh-Hans"
      }
    }
  }
]
